### PR TITLE
Fix the fullscreenEnabled attribute for Firefox

### PR DESCRIPTION
**Pull request by GuillaumeAmat**

### CODE REVIEW

**Comment by neovov** [comment]
Not sure if this is useful since Firefox use the unprefixed attributes now.

**Comment by GuillaumeAmat** [comment]
I'm using Firefox 38 (released this week) and it uses the prefixed one.
And it's good for retro compatibilty ;)

**Comment by neovov** [comment]
Sorry, my mistake I haven't checked enough, my Firefox **do** use prefixed attributes :).
Strange I didn't noticed this issue before.

Thanks :beers: !

**Comment by GuillaumeAmat** [comment]
You're welcome :)

**Comment by bummzack** [comment]
I think that change was wrong. 
Firefox uses `mozFullScreenEnabled` to indicate whether or not the fullscreen-API is available. It uses `mozFullScreen` to indicate whether or not the browser is currently in Fullscreen mode ([reference](https://developer.mozilla.org/en-US/docs/Web/API/document/mozFullScreen)).

If this should cover the same functionality as `webkitIsFullScreen`, then it has to be changed back to `mozFullScreen`.

**Comment by GuillaumeAmat** [comment]
If my memory is good, at that time the Firefox version was 38. And it raised me an error saying that mozFullScreen was not defined.
You need to verify that but if it's true, your change could break the compatibility with older versions of Firefox.

**Comment by bummzack** [comment]
According to the "Browser compatibility" table on the Mozilla developer documentation, it should be available since Firefox/Gecko 9.0 (that was released in 2011).

**Comment by GuillaumeAmat** [comment]
It « should »... I agree...

**Pull request merged**
